dist: trusty
sudo: required
services:
  - docker
language: go
go:
  - 1.13

script:
- make lint
- make test
- make vet
- make website-test

branches:
  only:
  - master
matrix:
  fast_finish: true
  allow_failures:
  - go: tip
